# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be31796b1b5969e679e0a743f6955b9b06b54854d8cd96d2479ea05e776cbeba458d2994c27d8baf562c5b3f48d2b95103d113cc1a7b2e3ce8eab2ae50f9e4d4

test:
  secret_key_base: 2548354229d36ba69025612b52ade2c64a0e8e0df45d362643f9a2b932677f580c1257c27be2c98cfe84eb8f89d7b90bbe0879b009dc154c1a387b1cfeb7bebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
